version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: '17 2 * * *'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: '37 2 * * *'
      timezone: America/Los_Angeles
